package datahub.core;

/**
 * Centralized constants for the DataHub project.
 */
public final class DataHubConstants {

    private DataHubConstants() {
        // Prevent instantiation
    }

    public static final String PROJECT_NAME = "DataHub";
    public static final String GENERATED_BY_COMMENT = "Generated by " + PROJECT_NAME;
}
