package datahub.core.services;

import datahub.core.DataHubConstants;
import datahub.core.contract.DBType;
import datahub.core.metadata.DataType;

/**
 * Abstract base class for DDL generators, providing common utility methods.
 */
public abstract class AbstractDdlGenerator<T extends DBType> implements DdlGenerator<T> {

    /**
     * Helper to get the standard "Generated by..." comment.
     *
     * @return The comment string.
     */
    protected String getGeneratedByComment() {
        return DataHubConstants.GENERATED_BY_COMMENT;
    }

    /**
     * Maps a core DataType to a SQL type string.
     * Subclasses should override this if they need specific type mappings.
     *
     * @param dataType The core data type.
     * @return The SQL type string.
     */
    protected String mapDataTypeToSql(DataType dataType) {
        return switch (dataType) {
            case BIGINT -> "BIGINT";
            case INT -> "INT";
            case DOUBLE -> "DOUBLE";
            case BOOLEAN -> "BOOLEAN";
            case DECIMAL -> "DECIMAL";
            case STRING -> "STRING";
            case DATE -> "DATE";
            case TIMESTAMP_MILLIS -> "TIMESTAMP(3)";
            case TIMESTAMP_MICROS -> "TIMESTAMP(6)";
            case ARRAY -> "ARRAY<STRING>"; // Simplified default
            case MAP -> "MAP<STRING, STRING>"; // Simplified default
            case STRUCT -> "STRUCT"; // Simplified default
            default -> "STRING";
        };
    }
}
