package datahub.hudi;

import datahub.core.contract.Table;
import datahub.core.contract.TableName;
import datahub.core.contract.TableNamespace;
import datahub.core.metadata.TypedSchema;
import datahub.core.TestSchemas;
import datahub.core.exceptions.SchemaValidationException;
import datahub.core.metadata.FieldImpl;
import datahub.core.metadata.DataType;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Validates the assembly and DDL generation for a complete Hudi table
 * definition.
 * This test ensures that the core schema objects are correctly translated into
 * Hudi-specific properties and SQL statements.
 */
class HudiTableDefinitionTest {

    /**
     * Simulates defining a Hudi table and generating the CREATE TABLE statement.
     */
    @Test
    void testHudiTableDdlGeneration() {
        // --- 1. Define Core Schema (from the centralized factory) ---
        TypedSchema coreSchema = TestSchemas.USER_SCHEMA;

        // --- 2. Define Hudi Properties (Specific Configuration) ---
        HudiProperties hudiProps = new HudiProperties();
        hudiProps.setProperty(HudiType.TableProperties.TABLE_TYPE_KEY, HudiType.TableProperties.MERGE_ON_READ);
        // Use fields defined in the core schema for key identification
        hudiProps.setProperty(HudiType.TableProperties.RECORD_KEY_FIELD_KEY, TestSchemas.ID_FIELD.getName());
        hudiProps.setProperty(HudiType.TableProperties.PRECOMBINE_FIELD_KEY, TestSchemas.CREATED_AT_FIELD.getName());
        hudiProps.setProperty(HudiType.TableProperties.PARTITION_FIELDS_KEY, "date_key"); // Assume a partition key

        // --- 3. Assemble the Final Table Definition ---
        Table<HudiType> userTable = new Table<>() {
            @Override
            public TableName getName() {
                return () -> "user_profile_mor";
            }

            @Override
            public TableNamespace getNamespace() {
                return () -> "analytics";
            }

            @Override
            public HudiProperties getProperties() {
                return hudiProps;
            }

            @Override
            public TypedSchema getSchema() {
                return coreSchema;
            }
        };

        // --- 4. Generate the DDL Statement ---
        HudiTableService tableService = new HudiTableService();
        String ddl = tableService.generateCreateStatement(userTable);

        // --- 5. Validation Assertions ---
        assertNotNull(ddl, "DDL statement must not be null.");

        // Check structural elements
        assertTrue(ddl.contains("CREATE TABLE IF NOT EXISTS analytics.user_profile_mor"),
                "DDL must include table name and namespace.");
        assertTrue(ddl.contains("PARTITIONED BY (date_key)"), "DDL must include the partition key.");
        assertTrue(ddl.contains("STORED AS HUDI"), "DDL must include STORED AS HUDI format.");

        // Check TBLPROPERTIES for Hudi configuration
        assertTrue(ddl.contains(
                "'" + HudiType.TableProperties.TABLE_TYPE_KEY + "'='" + HudiType.TableProperties.MERGE_ON_READ + "'"),
                "DDL must include MERGE_ON_READ table type.");
        assertTrue(ddl.contains(
                "'" + HudiType.TableProperties.RECORD_KEY_FIELD_KEY + "'='" + TestSchemas.ID_FIELD.getName() + "'"),
                "DDL must include the record key.");
        assertTrue(
                ddl.contains("'" + HudiType.TableProperties.PRECOMBINE_FIELD_KEY + "'='"
                        + TestSchemas.CREATED_AT_FIELD.getName() + "'"),
                "DDL must include the precombine key.");
        assertTrue(
                ddl.contains("'" + HudiType.TableProperties.PARTITION_FIELDS_KEY + "'='"
                        + "date_key" + "'"),
                "DDL must include the partition key.");

        // Check Avro Schema inclusion (Crucial for Hudi metadata)
        assertTrue(ddl.contains("'schema.external.avro.raw'='"), "DDL must include the generated Avro Schema.");
        assertTrue(ddl.contains("\"type\" : \"record\""), "The embedded Avro schema must be present and valid JSON.");

        // Check SQL Type mapping
        assertTrue(ddl.contains("id BIGINT COMMENT"), "ID field must be mapped to BIGINT SQL type.");
        assertTrue(ddl.contains("created_at_ts TIMESTAMP COMMENT"),
                "Timestamp field must be mapped to TIMESTAMP SQL type.");

        // Check Centralized Comment
        assertTrue(ddl.contains("'comment'='Generated by DataHub'"),
                "DDL must include the centralized DataHub comment.");
    }

    @Test
    void testMixedTimestampPrecision() {
        final TypedSchema mixedSchema = () -> java.util.List.of(
                new FieldImpl("ts_millis", DataType.TIMESTAMP_MILLIS, false, null),
                new FieldImpl("ts_micros", DataType.TIMESTAMP_MICROS, false, null));

        HudiProperties props = new HudiProperties();
        props.setProperty(HudiType.TableProperties.TABLE_TYPE_KEY, HudiType.TableProperties.COPY_ON_WRITE);
        props.setProperty(HudiType.TableProperties.RECORD_KEY_FIELD_KEY, "ts_millis");
        props.setProperty(HudiType.TableProperties.PRECOMBINE_FIELD_KEY, "ts_millis");
        props.setProperty(HudiType.TableProperties.PARTITION_FIELDS_KEY, "ts_millis");

        assertThrows(SchemaValidationException.class, () -> {
            new HudiTableBuilderImpl()
                    .withName(() -> "mixed_ts_table")
                    .withNamespace(() -> "test_db")
                    .withSchema(mixedSchema)
                    .withProperties(props)
                    .build();
        });
    }

    @Test
    void testConsistentTimestampPrecision() {
        final TypedSchema millisSchema = () -> java.util.List.of(
                new FieldImpl("ts1", DataType.TIMESTAMP_MILLIS, false, null),
                new FieldImpl("ts2", DataType.TIMESTAMP_MILLIS, false, null));

        HudiProperties props = new HudiProperties();
        props.setProperty(HudiType.TableProperties.TABLE_TYPE_KEY, HudiType.TableProperties.COPY_ON_WRITE);
        props.setProperty(HudiType.TableProperties.RECORD_KEY_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PRECOMBINE_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PARTITION_FIELDS_KEY, "ts1");

        assertDoesNotThrow(() -> {
            new HudiTableBuilderImpl()
                    .withName(() -> "consistent_ts_table")
                    .withNamespace(() -> "test_db")
                    .withSchema(millisSchema)
                    .withProperties(props)
                    .build();
        });
    }

    @Test
    void testEnforcedTimestampPrecisionSuccess() {
        final TypedSchema millisSchema = () -> java.util.List.of(
                new FieldImpl("ts1", DataType.TIMESTAMP_MILLIS, false, null));

        HudiProperties props = new HudiProperties();
        props.setProperty(HudiType.TableProperties.TABLE_TYPE_KEY, HudiType.TableProperties.COPY_ON_WRITE);
        props.setProperty(HudiType.TableProperties.RECORD_KEY_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PRECOMBINE_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PARTITION_FIELDS_KEY, "ts1");
        // Enforce MILLIS
        props.setProperty(HudiProperties.TIMESTAMP_PRECISION_KEY, "MILLIS");

        assertDoesNotThrow(() -> {
            new HudiTableBuilderImpl()
                    .withName(() -> "enforced_millis_table")
                    .withNamespace(() -> "test_db")
                    .withSchema(millisSchema)
                    .withProperties(props)
                    .build();
        });
    }

    @Test
    void testEnforcedTimestampPrecisionFailure() {
        final TypedSchema microsSchema = () -> java.util.List.of(
                new FieldImpl("ts1", DataType.TIMESTAMP_MICROS, false, null));

        HudiProperties props = new HudiProperties();
        props.setProperty(HudiType.TableProperties.TABLE_TYPE_KEY, HudiType.TableProperties.COPY_ON_WRITE);
        props.setProperty(HudiType.TableProperties.RECORD_KEY_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PRECOMBINE_FIELD_KEY, "ts1");
        props.setProperty(HudiType.TableProperties.PARTITION_FIELDS_KEY, "ts1");
        // Enforce MILLIS, but schema has MICROS
        props.setProperty(HudiProperties.TIMESTAMP_PRECISION_KEY, "MILLIS");

        assertThrows(SchemaValidationException.class, () -> {
            new HudiTableBuilderImpl()
                    .withName(() -> "enforced_fail_table")
                    .withNamespace(() -> "test_db")
                    .withSchema(microsSchema)
                    .withProperties(props)
                    .build();
        });
    }
}
